version: '3.8'

services:
  # Servidor de Base de Datos
  db:
    image: mariadb:10.4
    container_name: fc_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fc_database
      MYSQL_USER: user_fastcontact
      MYSQL_PASSWORD: password_seguro
    volumes:
      # CAMBIO CLAVE: Usamos el volumen nombrado para que los datos sean inmortales
      - fc_mysql_data:/var/lib/mysql
      # Mantenemos el init para la primera vez
      - ./fc_database.sql:/docker-entrypoint-initdb.d/fc_database.sql
    ports:
      - "3306:3306"

  # Servidor Web y PHP
  app:
    image: php:8.0-apache
    container_name: fc_app
    restart: always
    depends_on:
      - db
    volumes:
      # Asegúrate de que esta ruta sea correcta en tu máquina o usa rutas relativas como ./src
      - ./src:/var/www/html
    ports:
      - "8080:80"
    command: >
      sh -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: fc_jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

# Declaración de volúmenes oficiales
volumes:
  fc_mysql_data: